package com.morpheus.domain.diagnostic;

/** Stable machine-readable diagnostics emitted by MORPHEUS. */
public enum DiagnosticCode {
    NO_PROVIDER_FOUND,
    UNSUPPORTED_SOURCE,
    UNSUPPORTED_PROVIDER_SCHEMA,
    UNSUPPORTED_FORMAT_VERSION,
    MISSING_REQUIRED_CAPABILITY,
    OPTIONAL_CAPABILITY_UNAVAILABLE,
    MULTIPLE_PROVIDER_MATCHES,
    EXPLICIT_PROVIDER_INCOMPATIBLE,
    REMOTE_PROVIDER_REQUIRES_OPT_IN,
    INVALID_SOURCE,
    PARTIAL_INGESTION,
    IDENTITY_COLLISION,
    PROVIDER_COMPOSITION_CONFLICT,
    REQUIRED_PROVIDER_UNAVAILABLE
}
