package com.morpheus.application.lifecycle;

/** Machine-readable reason preventing a lifecycle transition. */
public enum ChangeLifecycleBlocker {
    INVALID_TRANSITION,
    MISSING_REQUIREMENTS,
    UNKNOWN_CRITICAL_CONSTRAINTS,
    MISSING_ACCEPTANCE_CRITERIA,
    MISSING_DESIGN,
    DESIGN_REQUIRED,
    MISSING_PLAN,
    KNOWN_BLOCKER,
    BLOCKING_ACCEPTANCE_CRITERION_FAILED,
    BLOCKING_ACCEPTANCE_CRITERION_UNVERIFIED,
    BACKWARD_TRANSITION_DISABLED,
    COMPLETED_REOPEN_DISABLED,
    ABANDONMENT_REASON_REQUIRED,
    ARCHIVED_REOPEN_NOT_ALLOWED
}
