package com.morpheus.application.quality;

/** Stable machine-readable quality findings emitted by MORPHEUS intelligence. */
public enum QualityFindingCode {
    ORPHAN_REQUIREMENT,
    IMPLEMENTATION_TASK_WITHOUT_REQUIREMENT,
    ACCEPTANCE_COVERAGE_UNAVAILABLE,
    CHANGE_WITHOUT_CURRENT_REQUIREMENT,
    CHANGE_COMPLETENESS_PARTIALLY_OBSERVABLE,
    LIFECYCLE_REQUIRED_FACT_UNAVAILABLE,
    LIFECYCLE_TRANSITION_BLOCKED,
    DESIGN_DECISION_WITHOUT_TRACE,
    DECISION_JUSTIFICATION_UNAVAILABLE,
    EXTERNAL_REFERENCE_UNVALIDATED,
    EXTERNAL_REFERENCE_UNRESOLVED,
    EXTERNAL_REFERENCE_STALE,
    EXTERNAL_REFERENCE_BROKEN
}
