package com.morpheus.application.operability;

/** Stable machine-readable diagnostics for local operations. */
public enum OperationalEventCode {
    SYNC_STARTED,
    SYNC_COMPLETED,
    SYNC_FAILED,
    SNAPSHOT_PUBLISH_STARTED,
    SNAPSHOT_PUBLISH_COMPLETED,
    SNAPSHOT_PUBLISH_FAILED,
    PROVIDER_READ_COMPLETED,
    PROVIDER_READ_FAILED,
    EXTERNAL_CALL_COMPLETED,
    EXTERNAL_CALL_FAILED,
    DATABASE_READY,
    DATABASE_NOT_READY,
    RECOVERY_CANDIDATE_FAILED,
    DATABASE_LOCKED,
    SECURITY_PATH_IGNORED,
    WRITE_PERMISSION_HARDENED,
    WRITE_PERMISSION_UNSUPPORTED
}
